### ISSUE TITLE
Add support for table of contents

### ISSUE THREAD

**Issue by fontclos** [dribia/dbt2pdf#4]
A simple table of contents with links to each model/macro would be handy.

**Comment by hribera** [comment]
@fontclos @airibarne A veure què us sembla. 

He creat funcions de zero per fer-ho perquè el que he vist que hi havia natiu a `fpdf2` no m'ha acabat de fer el pes. 

Faltaria el tema d'afegir links als noms de les seccions a la ToC (és un must?). Ho he començat, però li falta encara.
